'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18444
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18444.
'
Namespace GermanCities
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="OrteLookupSoap", [Namespace]:="http://www.mathertel.de/OrteLookup/")>  _
    Partial Public Class OrteLookup
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private OrteStartWithOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetPrefixedEntriesOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.TestWS.My.MySettings.Default.TestWS_GermanCities_OrteLookup
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event OrteStartWithCompleted As OrteStartWithCompletedEventHandler
        
        '''<remarks/>
        Public Event GetPrefixedEntriesCompleted As GetPrefixedEntriesCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.mathertel.de/OrteLookup/OrteStartWith", RequestNamespace:="http://www.mathertel.de/OrteLookup/", ResponseNamespace:="http://www.mathertel.de/OrteLookup/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function OrteStartWith(ByVal prefix As String) As String
            Dim results() As Object = Me.Invoke("OrteStartWith", New Object() {prefix})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub OrteStartWithAsync(ByVal prefix As String)
            Me.OrteStartWithAsync(prefix, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub OrteStartWithAsync(ByVal prefix As String, ByVal userState As Object)
            If (Me.OrteStartWithOperationCompleted Is Nothing) Then
                Me.OrteStartWithOperationCompleted = AddressOf Me.OnOrteStartWithOperationCompleted
            End If
            Me.InvokeAsync("OrteStartWith", New Object() {prefix}, Me.OrteStartWithOperationCompleted, userState)
        End Sub
        
        Private Sub OnOrteStartWithOperationCompleted(ByVal arg As Object)
            If (Not (Me.OrteStartWithCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent OrteStartWithCompleted(Me, New OrteStartWithCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.mathertel.de/OrteLookup/GetPrefixedEntries", RequestNamespace:="http://www.mathertel.de/OrteLookup/", ResponseNamespace:="http://www.mathertel.de/OrteLookup/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetPrefixedEntries(ByVal prefix As String) As String
            Dim results() As Object = Me.Invoke("GetPrefixedEntries", New Object() {prefix})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetPrefixedEntriesAsync(ByVal prefix As String)
            Me.GetPrefixedEntriesAsync(prefix, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetPrefixedEntriesAsync(ByVal prefix As String, ByVal userState As Object)
            If (Me.GetPrefixedEntriesOperationCompleted Is Nothing) Then
                Me.GetPrefixedEntriesOperationCompleted = AddressOf Me.OnGetPrefixedEntriesOperationCompleted
            End If
            Me.InvokeAsync("GetPrefixedEntries", New Object() {prefix}, Me.GetPrefixedEntriesOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetPrefixedEntriesOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetPrefixedEntriesCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetPrefixedEntriesCompleted(Me, New GetPrefixedEntriesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub OrteStartWithCompletedEventHandler(ByVal sender As Object, ByVal e As OrteStartWithCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class OrteStartWithCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub GetPrefixedEntriesCompletedEventHandler(ByVal sender As Object, ByVal e As GetPrefixedEntriesCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetPrefixedEntriesCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
End Namespace
